SEARCH_DIR(C:\work\hiasm\Elements\delphi\code\)
INPUT(
wprt0.o
C:\work\hiasm\Elements\delphi\code\allres.or
)
GROUP(
C:\work\hiasm\Elements\delphi\code\units\libpIf_arg.a
C:\work\hiasm\Elements\delphi\code\units\libphiRandom.a
C:\work\hiasm\Elements\delphi\code\units\libphiCase.a
C:\work\hiasm\Elements\delphi\code\units\libphiMT_AddData.a
C:\work\hiasm\Elements\delphi\code\units\libphiMT_Get.a
C:\work\hiasm\Elements\delphi\code\units\libphiGE_SpritePosition.a
C:\work\hiasm\Elements\delphi\code\units\libphiMemory.a
C:\work\hiasm\Elements\delphi\code\units\libphiMath.a
C:\work\hiasm\Elements\delphi\code\units\libphiMathParse.a
C:\work\hiasm\Elements\delphi\code\units\libphiMT_MultiMem.a
C:\work\hiasm\Elements\delphi\code\units\libphiGE_SpriteMove.a
C:\work\hiasm\Elements\delphi\code\units\libphiGE_Sprite.a
C:\work\hiasm\Elements\delphi\code\units\libphiPolyBase.a
C:\work\hiasm\Elements\delphi\code\units\libphiEditPolyMulti.a
C:\work\hiasm\Elements\delphi\code\units\libphiPolyMorphMulti.a
C:\work\hiasm\Elements\delphi\code\units\libphiRGN_OutlinePicture.a
C:\work\hiasm\Elements\delphi\code\units\libphiTransparentManager.a
C:\work\hiasm\Elements\delphi\code\units\libphiLayoutSpacer.a
C:\work\hiasm\Elements\delphi\code\units\libpWinLayout.a
C:\work\hiasm\Elements\delphi\code\units\libphiHintManager.a
C:\work\hiasm\Elements\delphi\code\units\libpDebug.a
C:\work\hiasm\Elements\delphi\code\units\libpShlObj.a
C:\work\hiasm\Elements\delphi\code\units\libpcommdlg.a
C:\work\hiasm\Elements\delphi\code\units\libpShellAPI.a
C:\work\hiasm\Elements\delphi\code\units\libpRichEdit.a
C:\work\hiasm\Elements\delphi\code\units\libpMessages.a
C:\work\hiasm\Elements\delphi\code\units\libpWinSock.a
C:\work\hiasm\Elements\delphi\code\units\libpWin.a
C:\work\hiasm\Elements\delphi\code\units\libphibase_96DAEA0.a
C:\work\hiasm\Elements\delphi\code\units\libphibase_9C7DDA8.a
C:\work\hiasm\Elements\delphi\code\units\libphiSafeMode.a
C:\work\hiasm\Elements\delphi\code\units\libphiTimer.a
C:\work\hiasm\Elements\delphi\code\units\libphiFor.a
C:\work\hiasm\Elements\delphi\code\units\libphiHub.a
C:\work\hiasm\Elements\delphi\code\units\libphiGE_GridSpace.a
C:\work\hiasm\Elements\delphi\code\units\libphiGE_SpriteArray.a
C:\work\hiasm\Elements\delphi\code\units\libphiMT_Add.a
C:\work\hiasm\Elements\delphi\code\units\libphiMMTimer.a
C:\work\hiasm\Elements\delphi\code\units\libphiDoData.a
C:\work\hiasm\Elements\delphi\code\units\libphiGE_Background.a
C:\work\hiasm\Elements\delphi\code\units\libphiMainForm.a
C:\work\hiasm\Elements\delphi\code\units\libphiGE_SpriteCollection.a
C:\work\hiasm\Elements\delphi\code\units\libphiGE_Scene.a
C:\work\hiasm\Elements\delphi\code\units\libphiPaintBox.a
C:\work\hiasm\Elements\delphi\code\units\libpShare.a
C:\work\hiasm\Elements\delphi\code\units\libpkol.a
C:\work\hiasm\Elements\delphi\code\units\libpWindows.a
C:\work\hiasm\Elements\delphi\code\units\libphiMainForm_96D809C.a
libpobjpas.a
libpsystem.a
C:\work\hiasm\Elements\delphi\code\units\libpBalls.a
)
